### PR TITLE
Fix multiline ternary, add named arguments

### LINKED ISSUE #386: A certain way of writing Ternary removes Syntax Highlighting of null
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Null value looses coloration when colon is written on same line
### Steps to Reproduce

See screenshots.

**Expected behavior:**

Screenshot 2020-03-26 at 09 59 26

**Actual behavior:**

Screenshot 2020-03-26 at 09 59 40

**Reproduces how often:**

Every time.

### Versions

- Atom    : 1.45.0
- Electron: 4.2.7
- Chrome  : 69.0.3497.128
- Node    : 10.11.0
- macOS: 10.15.4

### Additional Information

I raised the same issue earlier [here](https://github.com/bmewburn/vscode-intelephense/issues/1067) but was referred to report it here. The maintainer said:

>Issue belongs to this repository: https://github.com/atom/language-php
And is caused by null : interpreted as goto label.

### PR DESCRIPTION
**Pull request by KapitanOczywisty**
### Description of the Change

- fix issues with multiline ternaries #386 
- named arguments (PHP 8.0)

### Possible Drawbacks

none

### Applicable Issues

fix #386

### CODE REVIEW

File: spec/php-spec.coffee [hunk 1]
```diff
@@ -317,6 +317,22 @@ describe 'PHP grammar', ->
           expect(tokens[9]).toEqual value: ':', scopes: ["source.php", "keyword.operator.ternary.php"]
           expect(tokens[12]).toEqual value: '::', scopes: ["source.php", "keyword.operator.class.php"]
 
+        it 'should NOT tokenize goto label in ternary', ->
```
Comment (sadick254) [inline spec/php-spec.coffee:320]:
```suggestion
        it 'should NOT tokenize a ternary statement as a goto label', ->
```

**Review by sadick254 — COMMENTED** [review]
This already looks great. 👍

File: spec/php-spec.coffee (hunk 1 above)
Comment (KapitanOczywisty) [reply spec/php-spec.coffee]: @sadick254 👍

**Review by sadick254 — APPROVED** [review]
